### ISSUE TITLE
Allow changing geoplatform’s URL

### ISSUE THREAD

**Issue by tusbar** [etalab/udata-geoplatform#9]
I would like to be able to configure a `GEOPLATFORM_URL` so I can change it for different environments.

Are there any udata plugins that introduce settings? Or should it be an environment variable?

**Comment by abulte** [comment]
You can look at another plugin to see how we handle settings, eg https://github.com/opendatateam/udata-tabular-preview/, start from settings.py. Then this can be overridden in your udata.cfg.
